# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_order',
            field=models.BooleanField(default=False, verbose_name='On order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=75, unique=True, verbose_name='E-mail'),
        ),
    ]
