# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 19:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181207_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'shop_orders_cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('show_address', models.BooleanField(verbose_name='Show address')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery items',
                'db_table': 'shop_orders_delivery',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date order')),
                ('payment', models.CharField(max_length=100, verbose_name='Payment')),
                ('delivery', models.CharField(max_length=100, verbose_name='Delivery')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='House')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'shop_orders',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('vendor_code', models.CharField(max_length=100, unique=True, verbose_name='Vendor code')),
                ('url', models.CharField(max_length=400)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='shop/orders/', verbose_name='Image')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Price')),
                ('price_card', models.IntegerField(blank=True, default=0, verbose_name='Price card')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order good',
                'verbose_name_plural': 'Order goods',
                'db_table': 'shop_orders_goods',
                'ordering': ['-order__date_create', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
                'db_table': 'shop_orders_payments',
                'ordering': ['order'],
            },
        ),
    ]
