# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181230_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Purchase'), (1, 'Order')], default=0, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Good', verbose_name='Good'),
        ),
    ]
