# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190102_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergood',
            name='vendor_code',
            field=models.CharField(max_length=100, verbose_name='Vendor code'),
        ),
    ]
