# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190102_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sum'),
        ),
    ]
