# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190217_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(blank=True, default=0, verbose_name='Sum'),
        ),
    ]
