# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190217_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Price')),
                ('price_card', models.IntegerField(blank=True, default=0, verbose_name='Price card')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='Count')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
            ],
            options={
                'db_table': 'shop_regions_priceinshop',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('region_name', models.CharField(max_length=250, unique=True, verbose_name='Region Name')),
                ('default_region', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shop_regions_region',
                'ordering': ['region_name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('address', models.CharField(max_length=300)),
                ('delivery', models.CharField(default='', max_length=300)),
                ('goods_file', models.CharField(max_length=300)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=25)),
                ('default_shop', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Region')),
            ],
            options={
                'db_table': 'shop_regions_shop',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddField(
            model_name='priceinshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='priceinshop',
            unique_together=set([('shop', 'good')]),
        ),
    ]
