# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190717_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinshop',
            name='is_order',
            field=models.BooleanField(default=False, verbose_name='On order'),
        ),
    ]
