# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_priceinshop_is_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinshop',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Is hit'),
        ),
        migrations.AddField(
            model_name='priceinshop',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
        migrations.AddField(
            model_name='priceinshop',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Is sale'),
        ),
    ]
