# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='/', max_length=250, verbose_name='Url')),
                ('icon_name', models.CharField(max_length=20, verbose_name='Icon name')),
            ],
            options={
                'verbose_name': 'Bottom icon',
                'verbose_name_plural': 'Bottom icons',
                'db_table': 'website_icons_bottom',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BottomMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='/', max_length=250, verbose_name='Url')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.BottomMenu', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Bottom menu item',
                'verbose_name_plural': 'Bottom menu',
                'db_table': 'website_bottom_main',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('url', models.CharField(blank=True, default='/', max_length=250, verbose_name='Url')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='website/blocks/', verbose_name='Image')),
                ('type', models.CharField(blank=True, choices=[('', 'Category'), ('new', 'Is new'), ('sales', 'Is sale')], default='', max_length=5, verbose_name='Block type')),
            ],
            options={
                'verbose_name': 'Main page block',
                'verbose_name_plural': 'Main page blocks',
                'db_table': 'website_blocks_main',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='/', max_length=250, verbose_name='Url')),
                ('icon_name', models.CharField(max_length=2, verbose_name='Icon name')),
            ],
            options={
                'verbose_name': 'Social icon',
                'verbose_name_plural': 'Social icons',
                'db_table': 'website_social_icons',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.TextField(verbose_name='Html code')),
            ],
            options={
                'verbose_name': 'Statistic counter',
                'verbose_name_plural': 'Statistic counters',
                'db_table': 'website_statistic_counters',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
