# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Bottom menu address',
                'verbose_name_plural': 'Bottom menu addresses',
                'db_table': 'website_bottom_addresses',
            },
        ),
    ]
